pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/enyasystem/alx-backend-python.git', branch: 'main'
            }
        }
        stage('Install Dependencies & Run Tests') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                    pytest messaging_app --junitxml=report.xml
                '''
            }
        }
    }
    post {
        success {
            echo '✅ Pipeline succeeded!'
            junit 'report.xml'
        }
        failure {
            echo '❌ Pipeline failed!'
            junit 'report.xml'
        }
        always {
            echo 'Pipeline finished.'
        }
    }
}
